services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: final_django_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=final_django_db
      - DB_USER=user
      - DB_PASSWORD=user
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data: